#!/usr/local/bin/node --harmony

var fs = require('fs');
var pathJoin = require('path').join;
var groupDir = pathJoin(__dirname, "..", "groups");

var redirects = [];
var httpSites = {};
var httpsSites = {};

var extras = {
  "lit.luvit.io":
  "  location / {\n" +
  "    proxy_pass http://127.0.0.1:4822;\n" +
  "    proxy_http_version 1.1;\n" +
  "    proxy_set_header Host $host;\n" +
  "    proxy_set_header Upgrade $http_upgrade;\n" +
  "    proxy_set_header Connection \"upgrade\";\n" +
  "  }\n",
  "creationix.com":
  "  location /api/ {\n" +
  "    proxy_pass http://127.0.0.1:5000;\n" +
  "    proxy_http_version 1.1;\n" +
  "    proxy_set_header Host $host;\n" +
  "  }\n",
  "howtonode.org":
  "  location / {\n" +
  "    proxy_pass http://127.0.0.1:4000;\n" +
  "    proxy_http_version 1.1;\n" +
  "    proxy_set_header Host $host;\n" +
  "  }\n",
  "try.luvit.io":
  "  location / {\n" +
  "    proxy_pass http://127.0.0.1:1337;\n" +
  "    proxy_http_version 1.1;\n" +
  "    proxy_set_header Host $host;\n" +
  "    proxy_set_header Upgrade $http_upgrade;\n" +
  "    proxy_set_header Connection \"upgrade\";\n" +
  "  }\n",
  "static.creationix.com":
  "  location / {\n" +
  "    root /home/tim/static;\n" +
  "  }\n",
}

httpSites[extras["howtonode.org"]] = ["howtonode.org"];
httpSites[extras["static.creationix.com"]] = ["static.creationix.com"];
httpSites[extras["lit.luvit.io"]] = ["lit.luvit.io"];
httpsSites[extras["lit.luvit.io"]] = ["lit.luvit.io"];
httpsSites[extras["try.luvit.io"]] = ["try.luvit.io"];
redirects.push("try.luvit.io");

fs.readdirSync(groupDir).forEach(function (name) {
  var sitesConfig = require(pathJoin(groupDir, name));
  var sslSites = [];
  var sites = [];
  Object.keys(sitesConfig.sites).forEach(function (domain) {
    var config = sitesConfig.sites[domain];
    var root = config.root ? pathJoin("/", config.root, "/") : "/";

    var root = config.root ? pathJoin("/", config.root, "/") : "/";
    var backend = "http://127.0.0.1:" + sitesConfig.port + root;
    var proxy = extras[domain] || "";
    proxy +=
      "  location / {\n" +
      "    proxy_pass " + backend + ";\n" +
      "    proxy_http_version 1.1;\n" +
      "    proxy_set_header Host $host;\n";
    if (config.root) {
      proxy += "    proxy_redirect default;\n";
      proxy += "    proxy_redirect " + root + " /;\n";
    }
    proxy += "  }\n";

    var top = config.ssl ? httpsSites : httpSites;
    var list = top[proxy] || (top[proxy] = []);
    list.push(domain);

    if (config.ssl) {
      redirects.push(domain);
    }
  });
});

Object.keys(httpSites).forEach(function (proxy) {
  var list = httpSites[proxy];
  console.log(
    "server{\n" +
    list.map(serverName).join("") +
    "  listen 80;\n" +
    "  listen [::]:80;\n" +
    proxy +
    "}\n"
  );
});

Object.keys(httpsSites).forEach(function (proxy) {
  var list = httpsSites[proxy];
  list.forEach(function (domain) {
    console.log(
      "server{\n" +
      "  server_name " + domain + ";\n" +
      "  listen 443 ssl;\n" +
      "  listen [::]:443 ssl;\n" +
      "  ssl_certificate /home/tim/startssl/" + domain + "/ssl-unified.crt;\n" +
      "  ssl_certificate_key /home/tim/startssl/" + domain + "/ssl.key;\n" +
      "  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;\n" +
      "  ssl_prefer_server_ciphers on;\n" +
      '  ssl_ciphers "EECDH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384 EECDH+ECDSA+SHA256 EECDH+aRSA+SHA384 EECDH+aRSA+SHA256 EECDH+aRSA+RC4 EECDH EDH+aRSA RC4 !aNULL !eNULL !LOW !3DES !MD5 !EXP !PSK !SRP !DSS";\n' +
      proxy +
      "}\n"
    );
  });
});

if (redirects.length) {
  console.log(
    "\n# Combined force SSL redirects" +
    "\nserver {\n" +
    "  listen 80;\n" +
    "  listen [::]:80;\n" +
    redirects.map(serverName).join("") +
    "  return 301 https://$host$request_uri;\n" +
    "}"
  );
}

function serverName(domain) {
  return "  server_name " + domain + ";\n";
}
