#!/usr/local/bin/node

var fs = require('fs');
var pathJoin = require('path').join;
var childProcess = require("child_process");

var groupDir = pathJoin(__dirname, "../groups");
var scriptPath = pathJoin(__dirname, "../node_modules/wheaty/bin/wheaty-group.js");

fs.readdirSync(groupDir).forEach(function (name) {
  var configPath = pathJoin(groupDir, name);
  var config = require(configPath);
  var args = [scriptPath, configPath];
  var child;
  var started = Date.now();
  spawn();
  function spawn() {
    console.log("spawning", process.execPath, args);
    child = childProcess.spawn(process.execPath, args, {
      stdio: 'inherit'
    });
    child.on("exit", onExit);
  }
  function onExit(code, signal) {
    if (Date.now() - started > 1000 && code) spawn();
  }
});
